# Site settings
title: I Am Keerthan | Aditya Keerthan Life Journey
description: "In my short stint of 10 years, I practiced and preached how to help others"
url: "http://www.akhelpfoundation.com/"
author:
  name: "Aditya Keerthan"
  email: "Akhelpfoundation@gmail.com"
  url: "http://www.akhelpfoundation.com/"

# Build settings
baseurl: /emerald # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
