# Site settings
title: I Am Keerthan | My Help Foundation
description: "In my short stint of 10 years, I always believed in humans. Instantly. Keep up the humanity."
url: "http://www.akhelpfoundation.com"
author:
  name: "Aditya Keerthan Kanduri"
  email: "akhelpfoundation@gmail.com"
  url: "http://www.akhelpfoundation.com"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
